### ISSUE TITLE
--color-shadow variables undefined

### ISSUE THREAD

**Issue by hehehai** [CodyHouse/codyhouse-framework#13]
Local variables under element mouse events are not available

scss file code
``` scss
.ex-link {
  --color-shadow-1: hsla(var(--color-primary-h), var(--color-primary-s), var(--color-primary-l), 0.2); // fix iOS 12 bug
  box-shadow: 0 0 0 3px var(--color-shadow-1);

  &:hover {
    --color-shadow-2: hsla(var(--color-accent-h), var(--color-accent-s), var(--color-accent-l), 0.2); // fix iOS 12 bug
    box-shadow: 0 0 0 3px var(--color-shadow-2);
  }
}
```

Compile
``` css
.ex-link {
  --color-shadow-1: hsla(220, 90%, 56%, 0.2);
  --color-shadow-1: hsla(var(--color-primary-h), var(--color-primary-s), var(--color-primary-l), 0.2);
  box-shadow: 0 0 0 3px hsla(220, 90%, 56%, 0.2);
  box-shadow: 0 0 0 3px var(--color-shadow-1);
}
```
no events, that's work!

``` css
.ex-link:hover {
  --color-shadow-2: hsla(355, 90%, 61%, 0.2);
  --color-shadow-2: hsla(var(--color-accent-h), var(--color-accent-s), var(--color-accent-l), 0.2);
  box-shadow: undefined;
  box-shadow: 0 0 0 3px var(--color-shadow-2);
}

.ex-link:hover:hover {
  box-shadow: 0 0 0 3px hsla(355, 90%, 61%, 0.2);
  box-shadow: 0 0 0 3px var(--color-shadow-2);
}
```

![image](https://user-images.githubusercontent.com/12692552/54733272-c7931a80-4bd3-11e9-8052-032db9387e6f.png)

``` css
.form-control:focus {
  outline: none;
  border-color: hsl(220, 90%, 56%);
  border-color: var(--color-primary);
  --color-shadow: hsla(220, 90%, 56%, 0.2);
  --color-shadow: hsla(var(--color-primary-h), var(--color-primary-s), var(--color-primary-l), 0.2);
  box-shadow: undefined;
  box-shadow: 0 0 0 3px var(--color-shadow);
}

.form-control:focus:focus {
  box-shadow: 0 0 0 3px hsla(220, 90%, 56%, 0.2);
  box-shadow: 0 0 0 3px var(--color-shadow);
}
```

Just the problem after the code is compiled, the browser display is normal (including IE9)

fix
``` scss
.ex-link {
  --color-shadow-1: hsla(var(--color-primary-h), var(--color-primary-s), var(--color-primary-l), 0.2); // fix iOS 12 bug
  box-shadow: 0 0 0 3px var(--color-shadow-1);
  --color-shadow-2: hsla(var(--color-accent-h), var(--color-accent-s), var(--color-accent-l), 0.2); // fix iOS 12 bug

  &:hover {
    box-shadow: 0 0 0 3px var(--color-shadow-2);
  }
}
```
``` css
.ex-link {
  --color-shadow-1: hsla(220, 90%, 56%, 0.2);
  --color-shadow-1: hsla(var(--color-primary-h), var(--color-primary-s), var(--color-primary-l), 0.2);
  box-shadow: 0 0 0 3px hsla(220, 90%, 56%, 0.2);
  box-shadow: 0 0 0 3px var(--color-shadow-1);
  --color-shadow-2: hsla(355, 90%, 61%, 0.2);
  --color-shadow-2: hsla(var(--color-accent-h), var(--color-accent-s), var(--color-accent-l), 0.2);
}

.ex-link:hover {
  box-shadow: 0 0 0 3px hsla(355, 90%, 61%, 0.2);
  box-shadow: 0 0 0 3px var(--color-shadow-2);
}
```

**Comment by sebastiano-guerriero** [comment]
👋hi there! And thanks for the heads up. We're looking further into this, to find out if we can fix the plugin that generates the fallback.

**Comment by w3work** [comment]
I'm getting a similiar error when i implement the scss of the switch component.

This error shows up then:
`events.js:174
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'charCodeAt' of undefined
    at C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\fileadmin\prototyp\assets\scss\styles.css:794:3
    at module.exports (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-value-parser\lib\parse.js:17:20)
    at new ValueParser (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-value-parser\lib\index.js:7:18)
    at ValueParser (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-value-parser\lib\index.js:10:10)
    at transformValue (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-calc\dist\lib\transform.js:24:42)
    at _default (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-calc\dist\lib\transform.js:59:100)
    at C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-calc\dist\index.js:25:51
    at C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss\lib\container.js:135:18
    at Rule.each (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss\lib\container.js:101:16)
    at Rule.walk (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss\lib\container.js:131:17)
    at C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss\lib\container.js:148:24
Emitted 'error' event at:
    at Transform.onerror (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\readable-stream\lib\_stream_readable.js:640:52)
    at Transform.emit (events.js:189:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at Transform.afterTransform (_stream_transform.js:94:3)
    at Immediate.<anonymous> (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\gulp-postcss\index.js:93:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)`

If i comment out these lines, no error anymore:
`&:focus + .switch__label,
  &:active + .switch__label {
    --color-shadow: hsla(var(--color-primary-h), var(--color-primary-s), var(--color-primary-l), 0.2); // fix iOS 12 bug
    box-shadow: 0 0 0 3px var(--color-shadow);
  }`

**Comment by w3work** [comment]
I'm getting a similiar error when i implement the scss of the switch component.

This error shows up in terminal:
```javascript
events.js:174
      throw er; // Unhandled 'error' event
      ^
TypeError: Cannot read property 'charCodeAt' of undefined
    at C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\fileadmin\prototyp\assets\scss\styles.css:794:3
    at module.exports (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-value-parser\lib\parse.js:17:20)
    at new ValueParser (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-value-parser\lib\index.js:7:18)
    at ValueParser (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-value-parser\lib\index.js:10:10)
    at transformValue (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-calc\dist\lib\transform.js:24:42)
    at _default (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-calc\dist\lib\transform.js:59:100)
    at C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss-calc\dist\index.js:25:51
    at C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss\lib\container.js:135:18
    at Rule.each (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss\lib\container.js:101:16)
    at Rule.walk (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss\lib\container.js:131:17)
    at C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\postcss\lib\container.js:148:24
Emitted 'error' event at:
    at Transform.onerror (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\readable-stream\lib\_stream_readable.js:640:52)
    at Transform.emit (events.js:189:13)
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at Transform.afterTransform (_stream_transform.js:94:3)
    at Immediate.<anonymous> (C:\Users\sv20006\PhpstormProjects\mittelsaechsisches-theater.de\node_modules\gulp-postcss\index.js:93:9)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

If i comment out these lines, no error anymore:
```scss
&:focus + .switch__label,
  &:active + .switch__label {
    --color-shadow: hsla(var(--color-primary-h), var(--color-primary-s), var(--color-primary-l), 0.2); // fix iOS 12 bug
    box-shadow: 0 0 0 3px var(--color-shadow);
  }
```
