### ISSUE TITLE
CSS variables in media queries results in duplicated blocks

### ISSUE THREAD

**Issue by w3work** [CodyHouse/codyhouse-framework#15]
I have the strange problem in my compiled css, that there are duplicated blocks with the exact same css.

For example:
```scss
@supports (--css: variables) {
    @media (min-width: 64rem) {
      .main-footer__nav-item {
    margin-left: 1.5625em;
    margin-left: var(--space-md);
      }
    }
  }
@supports (--css: variables) {
    @media (min-width: 64rem) {
      .main-footer__nav-item {
    margin-left: 1.5625em;
    margin-left: var(--space-md);
      }
    }
  }
```
It seems there is a bug with the postcss-css-variables Plugin.
See here the issue: https://github.com/MadLittleMods/postcss-css-variables/issues/67

Do you have a idea how to fix that?
