### ISSUE TITLE
Better text sizing?

### ISSUE THREAD

**Issue by loxy** [CodyHouse/codyhouse-framework#56]
Hi!

Your text scale system is really cool. But it can be improved, I think. If you add a `--text-base`, something like this:
```scss
  // type scale
  --text-scale-ratio: 1.2;
  --text-xxs: calc(
    var(--text-base-size) /
      (var(--text-scale-ratio) * var(--text-scale-ratio) * var(--text-scale-ratio))
  );
  --text-xs: calc(var(--text-xxs) * var(--text-scale-ratio));
  --text-sm: calc(var(--text-xs) * var(--text-scale-ratio));
  --text-base: calc(var(--text-sm) * var(--text-scale-ratio));
  --text-md: calc(var(--text-base) * var(--text-scale-ratio));
  --text-lg: calc(var(--text-md) * var(--text-scale-ratio));
  --text-xl: calc(var(--text-lg) * var(--text-scale-ratio));
  --text-xxl: calc(var(--text-xl) * var(--text-scale-ratio));
  --text-xxxl: calc(var(--text-xxl) * var(--text-scale-ratio));
  --text-xxxxl: calc(var(--text-xxxl) * var(--text-scale-ratio));
```
it would be more consistent for the calculations. And now you can add

```scss
.text-base {
  font-size: var(--text-base, 1em); 
}
```

Or leave `--text-base` away and only use:
```scss
.text-base {
  font-size: var(--text-base-size, 1em); 
}
```

Because at the moment it is hard coded as:
```scss
.text-base {
  font-size: 1em;  // doesn't respect --text-base-size
}
```

Or did I miss something?
